version: '3.8'

services:
  app:
    image: financist-api
    build: 
      context: .
    ports:
      - "3000:3000"
    networks:
      - backend
    
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://user:password@postgres_db:5432/financist_database?schema=public
    command: npm run start:dev  # Usando o comando de desenvolvimento (hot reload)

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: financist_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres_db
    networks:
      - backend

  prisma_studio:
    image: node:20 # Pode usar uma imagem Node.js mais recente ou específica
    container_name: prisma_studio
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - backend
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres_db:5432/financist_database?schema=public
    command: npx prisma studio  # Comando para iniciar o Prisma Studio

volumes:
  postgres_data:
    driver: local

networks:
  backend:
    driver: bridge


