// <auto-generated />
using Financist.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Financist.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FinancistDbContext))]
    [Migration("20260428120000_AddDocumentChunks")]
    partial class AddDocumentChunks
    {
    }
}
